### ISSUE TITLE
Ruby/Node.js で 公開HTML生成用 CI 実行するための jykell テスト環境構築

### ISSUE THREAD

**Issue by mapconcierge** [furuhashilab/youthmappers4agu#38]
作業マニュアルの Development に記述されている環境構築をテスト。

https://github.com/furuhashilab/missingmaps.github.io/blob/publish/README.md#development

**Comment by mapconcierge** [comment]
作業ログ：

```
furuhasmacpro01:sl taichi$ gem install bundler
Fetching bundler-2.1.4.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
furuhasmacpro01:sl taichi$ sudo gem install bundler
Password:
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 2 seconds
1 gem installed
furuhasmacpro01:sl taichi$ sudo npm install -g gulp
sudo: npm: command not found
furuhasmacpro01:sl taichi$ which npm
/usr/local/bin/npm
furuhasmacpro01:sl taichi$ sudo npm install -g gulp
Password:
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js

> fsevents@1.2.13 install /usr/local/lib/node_modules/gulp/node_modules/fsevents
> node install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/taichi/Library/Caches/node-gyp/12.18.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/gulp/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/gulp/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/gulp/node_modules/fsevents
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
+ gulp@4.0.2
added 320 packages from 224 contributors in 10.671s
furuhasmacpro01:sl taichi$ sudo npm install --global gulp-cli
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/gulp-cli/bin/gulp.js
npm ERR! dest /usr/local/bin/gulp
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/gulp-cli/bin/gulp.js' -> '/usr/local/bin/gulp'
npm ERR! File exists: /usr/local/bin/gulp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taichi/.npm/_logs/2020-06-29T01_07_45_242Z-debug.log
furuhasmacpro01:sl taichi$ npm config get prefix
/usr/local

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/taichi/.config │
└───────────────────────────────────────────────────────────┘
furuhasmacpro01:sl taichi$ sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/taichi/.config │
└───────────────────────────────────────────────────────────┘

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/taichi/.config │
└───────────────────────────────────────────────────────────┘

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/taichi/.config │
└───────────────────────────────────────────────────────────┘
furuhasmacpro01:sl taichi$ sudo chown -R $USER:$(id -gn $USER) /Users/taichi/.config 
furuhasmacpro01:sl taichi$ sudo npm install -g gulp
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
+ gulp@4.0.2
updated 1 package in 5.591s
furuhasmacpro01:sl taichi$ npm install --global gulp-cli
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/gulp-cli/bin/gulp.js
npm ERR! dest /usr/local/bin/gulp
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/gulp-cli/bin/gulp.js' -> '/usr/local/bin/gulp'
npm ERR! File exists: /usr/local/bin/gulp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taichi/.npm/_logs/2020-06-29T01_11_51_308Z-debug.log
furuhasmacpro01:sl taichi$ sudo rm /usr/local/bin/gulp
furuhasmacpro01:sl taichi$ npm install --global gulp-cli
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp-cli/bin/gulp.js
+ gulp-cli@2.3.0
added 242 packages from 163 contributors in 5.338s
furuhasmacpro01:sl taichi$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/taichi/Documents/GitHub/sl/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/taichi/Documents/GitHub/sl/package.json'
npm WARN sl No description
npm WARN sl No repository field.
npm WARN sl No README data
npm WARN sl No license field.

up to date in 0.671s
found 0 vulnerabilities

furuhasmacpro01:sl taichi$ gem update --system
Updating rubygems-update
Fetching rubygems-update-3.1.4.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
furuhasmacpro01:sl taichi$ 

```

**Comment by mapconcierge** [comment]
# トラブル対処法

* npmでpermission deniedになった時の対処法[mac]
https://qiita.com/okohs/items/ced3c3de30af1035242d

* globalにgulp-cliをインストールしようとするとエラーが発生する
https://qiita.com/nayucolony/items/74f2c85253796b19c594

**Comment by mapconcierge** [comment]
sudo chown -R $USER:$(id -gn $USER) /Library/Ruby/Gems/2.6.0

**Comment by mapconcierge** [comment]
```
furuhasmacpro01:missingmaps.github.io taichi$ gulp serve
[11:50:33] Local modules not found in ~/Documents/GitHub/missingmaps.github.io
[11:50:33] Try running: npm install
furuhasmacpro01:missingmaps.github.io taichi$ npm install

> fsevents@1.2.12 install /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/fsevents
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> node-sass@4.13.1 install /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/darwin-x64-72_binding.node
Download complete░░⸩ ⠋ :
Binary saved to /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Caching binary to /Users/taichi/.npm/node-sass/4.13.1/darwin-x64-72_binding.node

> phantomjs-prebuilt@2.1.16 install /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/vb/2g3kj3gx2g1fvjh24rkw3zhh0000gq/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [=====================================---] 91%
Received 16746K total.
Extracting zip contents
Removing /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/vb/2g3kj3gx2g1fvjh24rkw3zhh0000gq/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1593399080175/phantomjs-2.1.1-macosx -> /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> node-sass@4.13.1 postinstall /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine

> missingmaps@0.2.0 install /Users/taichi/Documents/GitHub/missingmaps.github.io
> bundle install

Fetching gem metadata from https://rubygems.org/.........
Following files may not be writable, so sudo is needed:
  /usr/bin
Fetching public_suffix 4.0.3


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing public_suffix 4.0.3
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using bundler 2.1.4
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching concurrent-ruby 1.1.6
Installing concurrent-ruby 1.1.6
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /private/var/folders/vb/2g3kj3gx2g1fvjh24rkw3zhh0000gq/T/bundler20200629-42016-1jo0k8qeventmachine-1.2.7/gems/eventmachine-1.2.7/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20200629-42016-1r2bogr.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /var/folders/vb/2g3kj3gx2g1fvjh24rkw3zhh0000gq/T/bundler20200629-42016-1jo0k8qeventmachine-1.2.7/gems/eventmachine-1.2.7 for inspection.
Results logged to
/var/folders/vb/2g3kj3gx2g1fvjh24rkw3zhh0000gq/T/bundler20200629-42016-1jo0k8qeventmachine-1.2.7/extensions/universal-darwin-19/2.6.0/eventmachine-1.2.7/gem_make.out

An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll-feed was resolved to 0.13.0, which depends on
    jekyll was resolved to 4.0.0, which depends on
      em-websocket was resolved to 0.5.1, which depends on
        eventmachine
npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! missingmaps@0.2.0 install: `bundle install`
npm ERR! Exit status 5
npm ERR! 
npm ERR! Failed at the missingmaps@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taichi/.npm/_logs/2020-06-29T02_51_32_374Z-debug.log
furuhasmacpro01:missingmaps.github.io taichi$ 

```

**Comment by mapconcierge** [comment]
```
furuhasmacpro01:missingmaps.github.io taichi$ gulp serve
[11:54:34] Using gulpfile ~/Documents/GitHub/missingmaps.github.io/gulpfile.js
[11:54:34] Starting 'serve'...
[11:54:34] Starting 'clean'...
[11:54:34] Finished 'clean' after 7.89 ms
[11:54:34] Starting 'cloneEvents'...
[11:54:34] Starting 'cloneBlog'...
[11:54:34] Finished 'cloneEvents' after 14 ms
[11:54:34] Finished 'cloneBlog' after 15 ms
[11:54:34] Starting 'jekyll'...
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
[11:54:35] 'jekyll' errored after 219 ms
[11:54:35] Error: exited with error code: 127
    at ChildProcess.onexit (/Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:505:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[11:54:35] 'serve' errored after 245 ms
furuhasmacpro01:missingmaps.github.io taichi$ gem install bundler jekyll
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.
furuhasmacpro01:missingmaps.github.io taichi$ 

```

**Comment by mapconcierge** [comment]
現状の課題 gulp serve が動作していない。

当然以下のテストサイトもローカルで実行できていない。
http://localhost:3000/


```
furuhasmacpro01:missingmaps.github.io taichi$ pwd
/Users/taichi/Documents/GitHub/missingmaps.github.io

furuhasmacpro01:missingmaps.github.io taichi$ gulp serve
[12:11:34] Using gulpfile ~/Documents/GitHub/missingmaps.github.io/gulpfile.js
[12:11:34] Starting 'serve'...
[12:11:34] Starting 'clean'...
[12:11:34] Finished 'clean' after 7.9 ms
[12:11:34] Starting 'cloneEvents'...
[12:11:34] Starting 'cloneBlog'...
[12:11:34] Finished 'cloneEvents' after 14 ms
[12:11:34] Finished 'cloneBlog' after 15 ms
[12:11:34] Starting 'jekyll'...
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /Library/Ruby/Site/2.6.0/rubygems.rb:296:in `activate_bin_path'
/Library/Ruby/Site/2.6.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /Users/taichi/Documents/GitHub/missingmaps.github.io/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
[12:11:35] 'jekyll' errored after 76 ms
[12:11:35] Error: exited with error code: 1
    at ChildProcess.onexit (/Users/taichi/Documents/GitHub/missingmaps.github.io/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:505:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[12:11:35] 'serve' errored after 102 ms
furuhasmacpro01:missingmaps.github.io taichi$ 

```

**Comment by mapconcierge** [comment]
# トラブル対応検討

* gulpが実行出来なくてハマった時に確認したこと
https://qiita.com/maximum80/items/996b60a605073ba8516d
